name: red_lamp_of_fear
description: 'None'
publish_to: 'none'
version: 1.0.0


environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^5.3.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
